version: "3.3"
   
services:
  db:
    build:
      context: .
      dockerfile: ./docker/amd64/Dockerfile.takserver-db
    volumes:
      - "db_data:/var/lib/postgresql/data:z"
      - "./tak:/opt/tak:z"
    networks:
      tak:
        aliases:
          - tak-database
    ports:
      - 5234:5432 
    restart: unless-stopped
  tak:
    build:
      context: .
      dockerfile: ./docker/amd64/Dockerfile.takserver
    env_file:
      - .env
    volumes:
      - "./tak:/opt/tak:z"
    ports:
      - "7443:8443"
      - "7444:8444"
      - "7446:8446"
      - "7089:8089"
      - "7000:9000"
      - "7001:9001"
    networks:
      tak:
    depends_on:
      - db
    restart: unless-stopped
volumes:
  db_data:
networks:
  tak:
